pipeline {
    agent any
    // tools {
        // Make sure the 'maven' name matches the name defined in the Global Tool Configuration
        // maven 'maven'
    // }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete Job') {
            steps {
                echo 'Completed Job'
            }
        }
    }
}
